### ISSUE TITLE
The audio links won't work since July 30 Summer Double Issue

### ISSUE THREAD

**Issue by metafo** [KevenLi8888/The_Economist_Audio_Link_Generator#1]
Thank you for creating this marvelous repo. 
The Economist weekly edition was suspended for a week to take a summer rest so they combined July 30 and August 6 editions into one.

So issue August 13 issue should be 
[The Economist August 13 Audio Edition](https://audiocdn.economist.com/sites/default/files/AudioArchive/2022/20220813/Issue_9308_20220813_The_Economist_Full_edition.zip
) not [audio not available](https://audiocdn.economist.com/sites/default/files/AudioArchive/2022/20220813/Issue_9309_20220813_The_Economist_Full_edition.zip
)

We have to deduct 1 from the issue number. For example, "9309 20220813" should be "9308 20220813" instead.

I hope you could fix it. 
Thanks.

**Comment by iwanderer** [comment]
Won't work anymore. No matter the ones before August 13 which were available or after.
I think they have changed the rule.

**Comment by metafo** [comment]
> Won't work anymore. No matter the ones before August 13 which were available or after. I think they have changed the rule.

I partly fixed this.
Please check this: [](https://niceboy.online/The_Economist_Audio_Link_Generator/economistdownload.html)

**Comment by metafo** [comment]
> Won't work anymore. No matter the ones before August 13 which were available or after. I think they have changed the rule.

Check https://niceboy.online/The_Economist_Audio_Link_Generator/economistdownload.html

**Comment by KevenLi8888** [comment]
> > Won't work anymore. No matter the ones before August 13 which were available or after. I think they have changed the rule.
> 
> Check https://niceboy.online/The_Economist_Audio_Link_Generator/economistdownload.html

Thank you for fixing that! Is it possible to make a pull request so I can merge that into the repo?

**Comment by metafo** [comment]
> 
Sure. 
Thanks.
![image](https://user-images.githubusercontent.com/111051267/203857328-83c360d7-e1f0-4f62-8817-5a654f199455.png)

**Comment by KevenLi8888** [comment]
Fixed in https://github.com/KevenLi8888/The_Economist_Audio_Link_Generator/pull/2.

**Comment by KevenLi8888** [comment]
> Sure.
> Thanks.
> ![image](https://user-images.githubusercontent.com/111051267/203857328-83c360d7-e1f0-4f62-8817-5a654f199455.png)

I love the meme btw 😆

**Comment by metafo** [comment]
> 

Just forwarded from [Reddit's Programmer Humor](https://www.reddit.com/r/ProgrammerHumor/)

You could check the Reddit page if you like. They share jokes and funny stuff on programming almost every day.

It also shares some select content from Reddit to Twitter. Check here [PR0GRAMMERHUM0R](https://twitter.com/PR0GRAMMERHUM0R) 

Haha... Enjoy!

https://www.reddit.com/r/programmerhumor/comments/z2u35d

![image](https://user-images.githubusercontent.com/111051267/203859194-d7c8f23b-0576-4e48-af17-bb257a6b6e9f.png)
